site_name: Example Docs
plugins:
  - unity:
      sites:
      - subsite-a
      - siteb:
          path: subsite-b
      - subsite-c:
          mountpoint: mounted-at-c
  #- awesome-pages:
  #    filename: .nav
  - search

nav:
  - "Start Here (root)": "index.md"
  - "Nesting":
    - "subsite-b/index.md"
    - "subsite-c/subsection-1/page.md"
