site_name: My Docs
plugins:
  - unity:
      sites:
      - subsite-a
      - siteb:
          path: subsite-b
      - subsite-c:
          mountpoint: mounted-at-c
  - awesome-pages:
      filename: .nav